name: release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Extract information
        shell: bash
        run: |
          echo "PROJECT_VERSION=$(sed -n 's/^"version"':' "\(.*\)"/\1/p' extension.json | head -n1)"
          echo "PROJECT_VERSION=$(sed -n 's/^"version"':' "\(.*\)"/\1/p' extension.json | head -n1)" >> $GITHUB_ENV
          PKG_NAME=VectorMenuSidebar-master-v${PROJECT_VERSION}.tar.gz
          echo ::set-output name=PKG_NAME::${PKG_NAME}
      - name: zip
        run: tar -xzvf ${steps.package.outputs.PKG_NAME} i18n/ resoureces/ README.md VectorMenuSidebar.class.php extension.json
      - name: "Artifact upload: tarball"
        uses: actions/upload-artifact@master
        with:
          name: ${{ steps.package.outputs.PKG_NAME }}
          path: ${{ steps.package.outputs.PKG_NAME }}
      - name: "Artifact upload: tarball"
        uses: actions/upload-artifact@master
        with:
          name: ${{ steps.package.outputs.PKG_NAME }}
          path: ${{ steps.package.outputs.PKG_NAME }}
      - name: Publish archives and packages
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.package.outputs.PKG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
